export const IPC_EVENTS = {
  TERMINAL_DATA: 'event:terminal:data',
  THREAD_STATUS: 'event:thread:status',
  THREAD_RENAMED: 'event:thread:renamed',
  SANDBOX_IMAGE_BUILDING: 'event:sandbox:imageBuilding',
  SANDBOX_IMAGE_UPDATED: 'event:sandbox:imageUpdated',
  LOG_ENTRY: 'event:log',
  MESSAGE_APPENDED: 'event:message:appended',
  THREAD_POST_APPENDED: 'event:threadPost:appended',
  THREAD_CREATED: 'event:thread:created',
  THREAD_DELETED: 'event:thread:deleted',
  TRAY_THREADS_UPDATE: 'event:tray:threadsUpdate',
  TRAY_NAVIGATE_TO_THREAD: 'event:tray:navigateToThread',
  KANBAN_TASK_MOVED: 'event:kanban:taskMoved',
  KANBAN_TASK_CREATED: 'event:kanban:taskCreated',
  KANBAN_TASK_UPDATED: 'event:kanban:taskUpdated',
  KANBAN_TASK_DELETED: 'event:kanban:taskDeleted',
  KANBAN_STAGES_UPDATED: 'event:kanban:stagesUpdated',
  COUNCIL_RUN_UPDATED: 'event:council:runUpdated',
  COUNCIL_OUTCOME_SUBMITTED: 'event:council:outcomeSubmitted',
  VOICE_FLOW_START: 'event:voiceFlow:start',
  VOICE_FLOW_STOP: 'event:voiceFlow:stop',
  VOICE_FLOW_STOPPED: 'event:voiceFlow:stopped',
  VOICE_FLOW_DOWNLOAD_PROGRESS: 'event:voiceFlow:downloadProgress',
  VOICE_FLOW_TRANSCRIPT_SEGMENT: 'event:voiceFlow:transcriptSegment',
  MEETING_DETECTED: 'event:meeting:detected',
  MEETING_ENDED: 'event:meeting:ended',
  MEETING_DETECTOR_ERROR: 'event:meeting:detectorError',
  RECORDING_OVERLAY_STATE: 'event:recording:overlayState',
  RECORDING_CANCEL: 'event:recording:cancel',
  MEMORY_INDEX_STATUS: 'event:memory:indexStatus',
  SHUTDOWN_OVERLAY_STATE: 'event:shutdown:overlayState',
  SETTINGS_CHANGED: 'event:settings:changed',
  PROJECT_SAVED: 'event:project:saved',
  PROJECT_DELETED: 'event:project:deleted',
  PROJECT_CONFIG_UPDATED: 'event:project:configUpdated',
} as const;

export const TRAY_CHANNELS = {
  FOCUS_THREAD: 'tray:focusThread',
  OPEN_APP: 'tray:openApp',
  QUIT_APP: 'tray:quitApp',
} as const;
